// nginx-angular/src/app/home/home.component.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import { KeycloakService } from 'keycloak-angular';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html'
})
export class HomeComponent implements OnInit {
  fullName: string = 'Guest';
  constructor(public route: ActivatedRoute, private keycloak: KeycloakService) {
  }

  ngOnInit() {
    this.keycloak.isLoggedIn().then(isLoggedIn => {
      if (isLoggedIn) {
        this.keycloak.loadUserProfile().then(profile => {
          this.fullName = `${profile.firstName} ${profile.lastName}`;
        });
      }
    });
  }

}

<div class="card-deck mb-3" *ngIf="route.children.length === 0">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Welcome {{ fullName }}</h4>
      <p class="card-text">
        This application uses the built-in <b>REST, Search and Spatial engines</b> of
        <a target="_blank" href="https://www.sap.com/products/hana.html" role="button">SAP Hana</a>
        along with data from the
        <a target="_blank" href="https://www.acleddata.com/" role="button"> Armed Conflict Location & Event Data
          Project</a>. Choose one of the links on the left sidebar to get started.
      </p>
      <p class="card-text">
        <a target="_blank" href="https://www.sap.com/products/hana.html" role="button" class="mr-3">
          <img src="assets/img/hana.png" height="45" alt="hana" />
        </a>
        <a target="_blank" href="https://www.acleddata.com/" role="button">
          <img src="assets/img/acled.png" height="65" alt="acled" />
        </a>
      </p>
    </div>
  </div>
</div>

<div class="card-deck" *ngIf="route.children.length === 0">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Components</h4>
      <p class="card-text">
        This application was created using the
        <a target="_blank" href="https://angular.io/" role="button">Angular</a>
        framework, with the
        <a target="_blank" href="https://getbootstrap.com/" role="button">Bootstrap</a> based
        <a target="_blank" href="https://coreui.io/docs/getting-started/introduction/" role="button">coreui</a> theme.
      </p>
      <p class="card-text">
        <a target="_blank" href="https://angular.io/" role="button" class="mr-2">
          <img src="assets/img/angular.svg" height="70" alt="angular" />
        </a>
        <a target="_blank" href="https://getbootstrap.com/" role="button" class="mr-3">
          <img src="assets/img/bootstrap.svg" height="50" alt="bootstrap" />
        </a>
        <a target="_blank" href="https://coreui.io/docs/getting-started/introduction/" role="button">
          <img src="assets/img/coreui.svg" height="50" alt="coreui" />
        </a>
      </p>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Runtime frameworks</h4>
      <p class="card-text">
        This application runs on
        <a target="_blank" href="https://cloudplatform.sap.com/" role="button">
          SAP Cloud Platform
        </a>
        as well as a
        <a target="_blank" href="https://www.docker.com/" role="button">
          docker
        </a>
        container or as a
        <a target="_blank" href="https://www.nginx.com/" role="button">Nginx</a>
        application
      </p>
      <p class="card-text">
        <a target="_blank" href="https://cloudplatform.sap.com/" role="button" class="mr-2">
          <img src="assets/img/cf.png" height="30" alt="docker" />
        </a>
        <a target="_blank" href="https://www.docker.com" role="button" class="mr-4 mb-1">
          <img src="assets/img/docker.svg" height="50" alt="docker" class="mb-2"/>
        </a>
        <a target="_blank" href="https://www.nginx.com/" role="button">
          <img src="assets/img/nginx.svg" height="30" alt="nodejs" />
        </a>
      </p>
    </div>
  </div>
</div>
<router-outlet></router-outlet>

// rtwp-vue/src/components/Home.vue
<template>
  <span>
    <div class="card-deck">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Welcome {{ fullName }}</h4>
          <p class="card-text">This application was created using the following</p>
          <ul class="list-group">
            <li class="list-group-item">
              <a target="_blank" href="https://vuejs.org/" title="Vue.js framework">
                <img src="../assets/vue.svg" height="50" alt="Vue.js" /> Vue.js
              </a>
            </li>
            <li class="list-group-item">
              <a target="_blank" href="https://bootstrap-vue.org/" title="Bootstrap-Vue plugins">
                <img src="../assets/bootstrap-vue.png" height="55" alt="Bootstrap-Vue" /> Bootstrap Vue
              </a>
            </li>
            <li class="list-group-item">
              <a target="_blank" href="https://coreui.io/docs/getting-started/introduction" title="CoreUI theme">
                <img src="../assets/coreui.png" height="65" alt="core-ui" /> CoreUI theme
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Runtime frameworks</h4>
          <p class="card-text">This application source is deployable on</p>
          <ul class="list-group">
            <li class="list-group-item">
              <a target="_blank" href="https://cloudplatform.sap.com" title="SAP Cloud Platform">
                <img src="../assets/sap.png" height="45" alt="SAP Cloud Platform" /> SAP Cloud Platform
              </a>
            </li>
            <li class="list-group-item">
              <a target="_blank" href="https://nodejs.org" title="nodejs development application">
                <img src="../assets/nodejs.svg" height="55" alt="nodejs" class="ml-2 mr-2" /> nodejs dev application
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <router-view></router-view>
  </span>
</template>

<script>
export default {
  name: 'AppHome',
  computed: {
    fullName: function() {
      return (this.$keycloak ? this.$keycloak.fullName : 'Guest');
    }
  }
}
</script>
