// nginx-angular/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { MessageItem } from '../message/message-item';
import { MessageHistoryService } from '../message/message-history.service';
import { SidebarService } from '../sidebar/sidebar.service';
import { KeycloakService } from 'keycloak-angular';

@Component({
  styleUrls: ['./header.component.css'],
  selector: 'app-header',
  templateUrl: './header.component.html'
})
export class HeaderComponent implements OnInit {
  accountUrl: string;
  isLoggedIn: boolean = false;
  sidebarVisible: boolean = true;
  username: string = 'Guest';
  messages: MessageItem[];

  constructor(private messageHistoryService: MessageHistoryService, private sidebarService: SidebarService, private keycloak: KeycloakService) {
  }

  toggleSidebar(): void {
    this.sidebarService.toggleHide$.next();
  }

  doLogout(): void {
    if (this.isLoggedIn) {
      this.keycloak.logout();
    }
  }

  doAccount(): void {
    if (this.isLoggedIn) {
      window.open(this.accountUrl, '_blank');
    }
  }

  clear() {
    this.messageHistoryService.clear();
  }

  ngOnInit(): void {
    this.messages = this.messageHistoryService.getHistory();

    this.keycloak.isLoggedIn().then(isLoggedIn => {
      if (isLoggedIn) {
        this.isLoggedIn = true;
        this.username = this.keycloak.getUsername();

        const instance = this.keycloak.getKeycloakInstance();
        this.accountUrl = `${instance.authServerUrl}/realms/${instance.realm}/account`;
      }
    });
  }
}

<header class="c-header c-header-light c-header-fixed">
  <!-- shown in mobile view -->
  <button class="c-header-toggler c-class-toggler d-lg-none mfe-auto" type="button" (click)="toggleSidebar()">
    <i class="c-icon c-icon-lg cil-menu"></i>
  </button>
  <a class="c-header-brand d-lg-none c-header-brand-sm-up-center" routerLink="home">
    <img src="assets/img/NS2-logo-blue.svg" alt="NS2 logo" width="86" />
  </a>

  <!-- toggle sidebar -->
  <button class="c-header-toggler c-class-toggler mfs-3 d-md-down-none" type="button" (click)="toggleSidebar()" responsive="true">
    <i class="c-icon c-icon-lg cil-menu"></i>
  </button>

  <!-- top right menu -->
  <ul class="c-header-nav ml-auto">
    <!-- notification menu-->
    <li class="c-header-nav-item dropdown d-md-down-none mx-2" dropdown placement="bottom right">
      <a class="c-header-nav-link dropdown-toggle app-no-caret" href role="button" aria-haspopup="true" aria-expanded="false" dropdownToggle (click)="(false)">
        <i class="c-icon cil-bell"></i><span class="badge badge-pill badge-info" *ngIf="messages.length > 0">{{ messages.length }}</span>
      </a>
      <div *dropdownMenu class="dropdown-menu dropdown-menu-right dropdown-menu-lg pt-0 app-scrollable-menu">
        <div class="dropdown-header bg-light text-center app-pointer" (click)="clear()"><strong class="app-underline">Clear Events</strong></div>
        <a class="dropdown-item" *ngFor="let item of messages"><i class="mr-1 c-icon {{ item.classes }}"></i> {{ item.text }} </a>
      </div>
    </li>

    <!-- User Menu -->
    <li class="c-header-nav-item d-md-down-none mx-2 dropdown" dropdown placement="bottom right">
      <a class="c-header-nav-link dropdown-toggle mr-2" href role="button" aria-haspopup="true" aria-expanded="false" dropdownToggle (click)="(false)">
        <i class="mr-1 c-icon cil-user"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right pt-0" aria-labelledby="navbarDropdown" *dropdownMenu>
        <div class="dropdown-header bg-light text-center">
          <strong>{{ username }}</strong>
        </div>
        <a class="dropdown-item app-pointer" (click)="doAccount()"><i class="mr-1 c-icon cil-shield-alt"></i> Account</a>
        <a class="dropdown-item app-pointer" (click)="doLogout()"><i class="mr-1 c-icon cil-account-logout"></i> Logout</a>
      </div>
    </li>
  </ul>

  <!-- breadcrumbs-->
  <div class="c-subheader justify-content-between px-3">
    <app-breadcrumb></app-breadcrumb>
  </div>
</header>

// rtwp-admin/src/components/Header.vue
<template>
  <header class="c-header c-header-light c-header-fixed">
    <!-- shown in mobile view -->
    <button
      class="c-header-toggler c-class-toggler d-lg-none mfe-auto"
      type="button"
      @click="toggleSidebar"
    >
      <i class="c-icon c-icon-lg cil-menu"></i>
    </button>
    <router-link
      class="c-header-brand d-lg-none c-header-brand-sm-up-center"
      to="/"
    >
      <img src="../assets/NS2-logo-blue.svg" alt="NS2 logo" width="86" />
    </router-link>

    <!-- toggle sidebar -->
    <button
      class="c-header-toggler c-class-toggler mfs-3 d-md-down-none"
      type="button"
      responsive="true"
      @click="toggleSidebar"
    >
      <i class="c-icon c-icon-lg cil-menu"></i>
    </button>

    <!-- top right menu -->
    <ul class="c-header-nav ml-auto">
      <!-- notification menu-->
      <b-nav-item-dropdown
        ref="dropdown"
        toggle-class="c-header-nav-link"
        class="c-header-nav-item d-md-down-none mx-2 dropdown app-dropdown"
        size="lg"
        right
        no-caret
      >
        <template v-slot:button-content>
          <a role="button">
            <i class="c-icon cil-bell"></i>
            <span
              class="badge badge-pill badge-info"
              v-if="messages.length > 0"
              >{{ messages.length }}</span
            >
          </a>
        </template>
        <b-dropdown-header
          class="bg-light text-center app-pointer"
          @click="clear"
        >
          <strong class="app-underline">Clear Events</strong>
        </b-dropdown-header>
        <b-dropdown-item v-for="(msg, key) in messages" :key="key">
          <i :class="[msg.iconClass, msg.textClass]" class="mr-2 c-icon"></i>
          {{ msg.text }}
        </b-dropdown-item>
      </b-nav-item-dropdown>

      <!-- User Menu -->
      <b-nav-item-dropdown
        toggle-class="c-header-nav-link"
        class="c-header-nav-item mx-2 dropdown app-dropdown"
        size="lg"
        right
        no-caret
      >
        <template v-slot:button-content>
          <a role="button">
            <i class="mr-1 c-icon cil-user"></i>
          </a>
        </template>
        <b-dropdown-header class="bg-light text-center">
          <strong>{{ userName }}</strong>
        </b-dropdown-header>
        <b-dropdown-item @click="doAccount">
          <i class="mr-1 c-icon cil-shield-alt"></i> Account
        </b-dropdown-item>
        <b-dropdown-item @click="doLogout">
          <i class="mr-1 c-icon cil-account-logout"></i> Logout
        </b-dropdown-item>
      </b-nav-item-dropdown>
    </ul>

    <AppBreadcrumbs />
  </header>
</template>

<script>
import AppBreadcrumbs from './Breadcrumbs.vue'
import { mapState } from 'vuex'

export default {
  name: 'AppHeader',
  components: {
    AppBreadcrumbs
  },
  computed: {
    ...mapState(['messages']),
    userName: function () {
      return this.$keycloak ? this.$keycloak.userName : 'Guest'
    }
  },
  methods: {
    toggleSidebar() {
      this.$store.commit('toggleSidebarShown')
    },
    doAccount() {
      if (this.$keycloak) {
        this.$keycloak.accountManagement()
      }
    },
    doLogout() {
      if (this.$keycloak) {
        this.$keycloak.logoutFn()
      }
    },
    clear() {
      this.$store.commit('clearMessages')
      this.$refs.dropdown.hide(true)
    }
  }
}
</script>

<style>
/* style fix for dropdown menu */
.app-dropdown > ul {
  right: auto !important;
  height: auto;
  max-height: 500px;
  overflow-x: hidden;
  padding-top: 0px !important;
}
.app-pointer {
  cursor: pointer !important;
}

.app-underline:hover {
  text-decoration: underline;
}
</style>
