// nginx-angular/src/app/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { SidebarService } from './sidebar.service';
import { DeviceDetectorService } from 'ngx-device-detector';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  host: { 'class': 'c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-show' }
})
export class SidebarComponent implements OnInit {
  isMin = false;

  constructor(private sidebarService: SidebarService, private deviceService: DeviceDetectorService) {
  }

  closeOnMobile(): void {
    if (this.deviceService.isMobile()) {
      this.sidebarService.toggleHide$.next();
    }
  }

  toggleMin(): void {
    this.isMin = !this.isMin;
    this.sidebarService.toggleMin$.next();
  }

  mouseEnter(): void {
    if (this.isMin) {
      this.sidebarService.toggleMin$.next();
    }
  }

  mouseLeave(): void {
    if (this.isMin) {
      this.sidebarService.toggleMin$.next();
    }
  }

  ngOnInit() { }
}

<div class="c-sidebar-brand d-md-down-none">
  <a routerLink="home">
    <img class="c-sidebar-brand-full" src="assets/img/NS2-logo-white.svg" alt="NS2 logo" width="86" />
    <img class="c-sidebar-brand-minimized" src="assets/img/NS2-icon-white.svg" height="30" alt="NS2 Logo" />
  </a>
</div>
<ul class="c-sidebar-nav" (mouseenter)="mouseEnter()" (mouseleave)="mouseLeave()">
  <li class="c-sidebar-nav-item">
    <a class="c-sidebar-nav-link" routerLink="home/status" routerLinkActive="c-sidebar-nav-link-primary" (click)="closeOnMobile()">
      <i class="c-sidebar-nav-icon cil-speedometer"></i> Status
    </a>
  </li>
  <li class="c-sidebar-nav-item">
    <a class="c-sidebar-nav-link" routerLink="home/charts" routerLinkActive="c-sidebar-nav-link-primary" (click)="closeOnMobile()">
      <i class="c-sidebar-nav-icon cil-chart-pie"></i> Charts
    </a>
  </li>
  <li class="c-sidebar-nav-item">
    <a class="c-sidebar-nav-link" routerLink="home/analysis" routerLinkActive="c-sidebar-nav-link-primary" (click)="closeOnMobile()">
      <i class="c-sidebar-nav-icon cil-puzzle"></i> Analysis
    </a>
  </li>
  <li class="c-sidebar-nav-item">
    <a class="c-sidebar-nav-link" routerLink="home/event" routerLinkActive="c-sidebar-nav-link-primary" (click)="closeOnMobile()">
      <i class="c-sidebar-nav-icon cil-list"></i> Events
    </a>
  </li>
  <li class="c-sidebar-nav-item">
    <a class="c-sidebar-nav-link" routerLink="home/search" routerLinkActive="c-sidebar-nav-link-primary" (click)="closeOnMobile()">
      <i class="c-sidebar-nav-icon cil-magnifying-glass"></i> Search
    </a>
  </li>
  <li class="c-sidebar-nav-item">
    <a class="c-sidebar-nav-link" routerLink="home/map" routerLinkActive="c-sidebar-nav-link-primary" (click)="closeOnMobile()">
      <i class="c-sidebar-nav-icon cil-map"></i> Map
    </a>
  </li>
  <li class="c-sidebar-nav-item">
    <a class="c-sidebar-nav-link" href="https://github.com/mechevarria" target="_blank" (click)="closeOnMobile()">
      <i class="c-sidebar-nav-icon cib-github"></i> Github
    </a>
  </li>
</ul>
<button class="c-sidebar-minimizer c-class-toggler" type="button" (click)="toggleMin()"></button>

// rtwp-admin/src/components/Sidebar.vue
<template>
  <div
    class="c-sidebar c-sidebar-dark c-sidebar-fixed"
    :class="{ 'c-sidebar-minimized': isSidebarMin, 'c-sidebar-show': isSidebarShown }"
    id="sidebar"
  >
    <div class="c-sidebar-brand d-md-down-none">
      <router-link to="/">
        <img
          class="c-sidebar-brand-full"
          src="../assets/NS2-logo-white.svg"
          alt="NS2 logo"
          width="86"
        />
        <img
          class="c-sidebar-brand-minimized"
          src="../assets/NS2-icon-white.svg"
          height="30"
          alt="NS2 Logo"
        />
      </router-link>
    </div>
    <ul class="c-sidebar-nav" @mouseenter="mouseEnter" @mouseleave="mouseLeave">
      <li class="c-sidebar-nav-item">
        <router-link class="c-sidebar-nav-link" to="/home/map" @click.native="closeOnMobile">
          <i class="c-sidebar-nav-icon cil-map"></i> Labs Map
        </router-link>
      </li>
      <li class="c-sidebar-nav-item">
        <router-link class="c-sidebar-nav-link" to="/home/visitors" @click.native="closeOnMobile">
          <i class="c-sidebar-nav-icon cil-people"></i> Visitors
        </router-link>
      </li>
      <li class="c-sidebar-nav-item">
        <router-link class="c-sidebar-nav-link" to="/home/status" @click.native="closeOnMobile">
          <i class="c-sidebar-nav-icon cil-speedometer"></i> Status
        </router-link>
      </li>
      <li class="c-sidebar-nav-item">
        <router-link class="c-sidebar-nav-link" to="/home/about" @click.native="closeOnMobile">
          <i class="c-sidebar-nav-icon cil-code"></i> About
        </router-link>
      </li>
      <li class="c-sidebar-nav-item">
        <a class="c-sidebar-nav-link" href="https://github.com/openNS2" target="_blank">
          <i class="c-sidebar-nav-icon cib-github"></i> Github
        </a>
      </li>
    </ul>
    <button class="c-sidebar-minimizer c-class-toggler" type="button" @click="toggleMin"></button>
  </div>
</template>

<script>
import { mapState } from 'vuex'

export default {
  name: 'AppSidebar',
  data() {
    return {
      isMouseEnter: false
    }
  },
  computed: mapState(['isSidebarMin', 'isSidebarShown']),
  methods: {
    toggleMin() {
      this.$store.commit('toggleSidebarMin')
    },
    mouseEnter() {
      if (this.isSidebarMin) {
        this.$store.commit('sidebarMax')
        this.isMouseEnter = true
      }
    },
    mouseLeave() {
      if (this.isMouseEnter) {
        this.$store.commit('sidebarMin')
        this.isMouseEnter = false
      }
    },
    closeOnMobile() {
      if (this.$isMobile()) {
        this.$store.commit('sidebarHide')
      }
    }
  },
  created() {
    if (this.$isMobile() && this.isSidebarShown) {
      this.$store.commit('sidebarHide')
    }
  }
}
</script>
