// nginx-angular/src/app/status/status.component.ts
import { Component, OnInit } from '@angular/core';
import { StatusService } from './status.service';
import { MessageService } from '../message/message.service';

@Component({
  selector: 'app-status',
  templateUrl: './status.component.html',
  styleUrls: ['./status.component.css']
})
export class StatusComponent implements OnInit {
  response: any = {};
  name: string = '';
  api: string = 'springboot-api/status';
  isBusy: boolean = false;

  constructor(private statusService: StatusService, private messageService: MessageService) { }

  checkApi(): void {
    this.isBusy = true;
    this.statusService.getStatus(this.api, this.name).subscribe(res => {
      this.isBusy = false;
      this.response = res;

      if (this.response.status === 200) {
        this.messageService.success(`Successfully checked ${this.api}`);
      }
    });
  }

  clear(): void {
    this.name = '';
    this.response = {};
  }

  ngOnInit(): void {
  }

}

<div class="card-deck mb-3">
  <div class="card">
    <div class="card-header">Check the Microservice REST api</div>
    <form class="card-text" (ngSubmit)="checkApi()" #userForm="ngForm" autocomplete="off">
      <div class="card-body">
        <div class="form-group">
          <label>Name</label>
          <input name="name" type="text" class="form-control" [(ngModel)]="name">
        </div>
        <div class="form-check">
          <input name="api" type="radio" class="form-check-input" value="springboot-api/status" [(ngModel)]="api">
          <label class="form-check-label mt-1"><i class="cib-spring"></i> Spring Boot</label>
        </div>
        <div class="form-check">
          <input name="api" type="radio" class="form-check-input" value="express-api/status" [(ngModel)]="api">
          <label class="form-check-label mt-1"><i class="cib-node-js"></i> Express</label>
        </div>
      </div>
      <div class="card-footer">
        <button type="submit" class="btn btn-sm btn-primary mr-1" [disabled]="isBusy">
          <span class="spinner-border spinner-border-sm" *ngIf="isBusy"></span> Submit
        </button>
        <button type="button" class="btn btn-sm btn-danger" (click)="clear()" [disabled]="isBusy">Clear</button>
      </div>
    </form>
  </div>
</div>

<div class="card-deck">
  <div class="card">
    <div class="card-header">Response</div>
    <div class="card-body">
      <div class="card-text">
        <pre>{{ response | json }}</pre>
      </div>
    </div>
  </div>
</div>

// rtwp-admin/src/components/Status.vue
<template>
  <div class="card-deck">
    <div class="card">
      <div class="card-header">Api Status</div>
      <form class="card-text" @submit.prevent="handleSubmit">
        <div class="card-body">
          <div class="form-group">
            <label>Name</label>
            <input v-model="text" type="text" class="form-control" />
          </div>
        </div>
        <div class="card-footer">
          <button
            type="submit"
            class="btn btn-sm btn-primary mr-1"
            :disabled="isBusy"
          >
            <i class="cil-check-circle btn-icon mr-1" v-if="!isBusy"></i>
            <i class="spinner-border spinner-border-sm mr-1" v-if="isBusy"></i>
            Submit
          </button>
          <button
            type="button"
            class="btn btn-sm btn-danger"
            @click="clear"
            :disabled="isBusy"
          >
            <i class="cil-x-circle btn-icon mr-1"></i>Clear
          </button>
        </div>
      </form>
    </div>
    <div class="card">
      <div class="card-header">Response</div>
      <div class="card-body">
        <pre>{{ data }}</pre>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios'
import msgMixin from '../mixins/msg-mixin'

export default {
  name: 'AppStatus',
  mixins: [msgMixin],
  data() {
    return {
      text: null,
      data: {},
      type: 'success',
      isBusy: false
    }
  },
  methods: {
    handleSubmit() {
      this.isBusy = true
      const options = {
        params: {
          text: this.text
        }
      }
      const url = '/btwp-api/status'
      axios
        .get(url, options)
        .then((res) => {
          this.data = res.data
          this.successMsg('Successfully checked btwp-api')
        })
        .catch((err) => {
          console.error(err)
          this.errorMsg(err.message)
        })
        .finally(() => {
          this.isBusy = false
        })
    },
    clear() {
      this.text = null
    }
  }
}
</script>
